services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: express_ecommerce_container
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   networks:
  #     - express_network

  db:
    image: postgres
    container_name: postgres_container_minpro
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "7654:5432"
    networks:
      - express_network

  redis:
    image: redis
    container_name: redis_container_minpro
    restart: always
    volumes:
      - ./docker/redis:/data
    ports:
      - "6379:6379"
    networks:
      - express_network

networks:
  express_network:
